#!/bin/bash
set -e


USERNAME=openshr
USERADD=/usr/sbin/useradd
ADDGROUP=/usr/sbin/addgroup
ADDUSER=/usr/sbin/adduser

service openshr stop || true

if ! getent group $USERNAME >/dev/null; then
    echo "Creating group $USERNAME"
    $ADDGROUP --quiet --system $USERNAME
fi


if id -u $USERNAME >/dev/null 2>&1; then
    echo "System user $USERNAME exists."
else
    echo "System user $USERNAME does not exist. adding."
    $USERADD  $USERNAME -g $USERNAME -M -s /bin/bash 
fi

exit 0



